version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: dependencies'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - 'type: dependencies'
